use strict;
use warnings;

$|=-1;


sub main{
	
	my $newtext = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod in pellentesque massa placerat duis ultricies lacus sed. Vulputate odio ut enim blandit. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Natoque penatibus et magnis dis parturient montes. Accumsan tortor posuere ac ut consequat semper viverra nam. In hac habitasse platea dictumst quisque. Scelerisque eleifend donec pretium vulputate. Mattis ullamcorper velit sed ullamcorper morbi. Ultricies mi quis hendrerit dolor magna eget est.

Sed augue lacus viverra vitae congue eu consequat ac felis. Libero enim sed faucibus turpis. Orci dapibus ultrices in iaculis. Eget mi proin sed libero enim sed. At lectus urna duis convallis. Odio ut enim blandit volutpat maecenas volutpat. Ipsum dolor sit amet consectetur adipiscing elit duis tristique. Morbi tincidunt ornare massa eget. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Praesent elementum facilisis leo vel fringilla est ullamcorper. Viverra maecenas accumsan lacus vel facilisis volutpat. Egestas tellus rutrum tellus pellentesque eu. Scelerisque fermentum dui faucibus in ornare. Gravida in fermentum et sollicitudin ac orci phasellus egestas tellus. Tempus quam pellentesque nec nam. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Nisi scelerisque eu ultrices vitae auctor. Senectus et netus et malesuada fames ac turpis egestas sed. Adipiscing enim eu turpis egestas pretium aenean pharetra.

Nunc congue nisi vitae suscipit tellus mauris. Blandit cursus risus at ultrices mi tempus imperdiet. Nibh cras pulvinar mattis nunc sed blandit libero. Eget felis eget nunc lobortis mattis aliquam faucibus purus. Ac tortor vitae purus faucibus ornare. Tristique sollicitudin nibh sit amet commodo. Eleifend donec pretium vulputate sapien nec. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Habitant morbi tristique senectus et netus et. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Tristique senectus et netus et malesuada. Turpis cursus in hac habitasse platea dictumst quisque sagittis. Amet porttitor eget dolor morbi non arcu. Id eu nisl nunc mi ipsum.

Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Eget mauris pharetra et ultrices. Fames ac turpis egestas integer eget aliquet nibh praesent. Pretium lectus quam id leo in. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. At volutpat diam ut venenatis tellus in metus vulputate eu. Id aliquet risus feugiat in. Nisl purus in mollis nunc. Amet volutpat consequat mauris nunc congue. Est ante in nibh mauris cursus mattis. Pharetra vel turpis nunc eget lorem dolor sed viverra. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl. At lectus urna duis convallis convallis. Nunc consequat interdum varius sit amet mattis vulputate enim nulla. Neque ornare aenean euismod elementum nisi quis eleifend. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Et leo duis ut diam quam. Non sodales neque sodales ut etiam sit amet.

Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Accumsan sit amet nulla facilisi morbi tempus iaculis. Consequat mauris nunc congue nisi vitae. Tincidunt praesent semper feugiat nibh sed pulvinar proin. Mi sit amet mauris commodo. Sit amet volutpat consequat mauris nunc. Sit amet nisl suscipit adipiscing bibendum est ultricies. Faucibus nisl tincidunt eget nullam non nisi. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. In vitae turpis massa sed elementum tempus egestas. Nibh sed pulvinar proin gravida hendrerit lectus a. Turpis massa sed elementum tempus egestas. Vel eros donec ac odio tempor orci dapibus. Diam sollicitudin tempor id eu nisl nunc mi. Blandit aliquam etiam erat velit scelerisque in dictum non. Pellentesque habitant morbi tristique senectus et. Orci dapibus ultrices in iaculis nunc sed augue. Proin sed libero enim sed faucibus turpis in eu.

Et ultrices neque ornare aenean euismod. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Euismod elementum nisi quis eleifend quam adipiscing vitae. Eu non diam phasellus vestibulum lorem sed. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper. Velit scelerisque in dictum non consectetur a erat nam. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Integer vitae justo eget magna fermentum iaculis eu non diam. Sem nulla pharetra diam sit amet nisl suscipit. Mollis nunc sed id semper risus in hendrerit gravida.

Lorem mollis aliquam ut porttitor leo. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Lectus nulla at volutpat diam ut. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Felis eget velit aliquet sagittis id. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Morbi leo urna molestie at elementum eu facilisis sed odio. Pulvinar pellentesque habitant morbi tristique senectus. Quis vel eros donec ac odio tempor orci dapibus. Amet risus nullam eget felis.

Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Placerat duis ultricies lacus sed turpis tincidunt id aliquet. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Ut tristique et egestas quis ipsum. Mauris pharetra et ultrices neque ornare. Integer vitae justo eget magna fermentum. Et molestie ac feugiat sed lectus vestibulum mattis. Fusce ut placerat orci nulla pellentesque dignissim enim. Massa tempor nec feugiat nisl pretium.

Ultrices eros in cursus turpis. Eget nulla facilisi etiam dignissim diam. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Imperdiet dui accumsan sit amet. Sociis natoque penatibus et magnis dis. Nisi quis eleifend quam adipiscing vitae. Tristique risus nec feugiat in fermentum posuere. Sit amet luctus venenatis lectus magna fringilla urna porttitor. In nisl nisi scelerisque eu ultrices vitae auctor. Amet mauris commodo quis imperdiet massa tincidunt. Blandit cursus risus at ultrices mi. Arcu risus quis varius quam quisque. Lacus viverra vitae congue eu consequat ac felis donec. Morbi tristique senectus et netus et malesuada fames ac turpis. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus.

Sit amet commodo nulla facilisi nullam vehicula ipsum. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Ac placerat vestibulum lectus mauris. Vulputate mi sit amet mauris commodo. Ullamcorper a lacus vestibulum sed. Auctor elit sed vulputate mi sit amet. Orci sagittis eu volutpat odio facilisis. Tincidunt id aliquet risus feugiat in ante metus. Eget dolor morbi non arcu risus quis varius. Sagittis purus sit amet volutpat. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Rhoncus urna neque viverra justo nec ultrices. Lorem mollis aliquam ut porttitor leo a diam. Morbi enim nunc faucibus a pellentesque sit amet porttitor eget. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Dolor purus non enim praesent elementum.

Egestas fringilla phasellus faucibus scelerisque. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Etiam tempor orci eu lobortis elementum nibh tellus molestie nunc. Nulla aliquet porttitor lacus luctus accumsan tortor. Ullamcorper eget nulla facilisi etiam. Arcu non odio euismod lacinia at quis risus. Sed nisi lacus sed viverra tellus in hac habitasse platea. Diam quam nulla porttitor massa id neque. Id consectetur purus ut faucibus. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Sed vulputate odio ut enim blandit volutpat maecenas. At urna condimentum mattis pellentesque id. Mi eget mauris pharetra et ultrices neque ornare aenean. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Vitae congue eu consequat ac felis donec et odio pellentesque. Pretium quam vulputate dignissim suspendisse in est ante. Arcu ac tortor dignissim convallis aenean et. Quis lectus nulla at volutpat diam ut venenatis tellus in. Pharetra vel turpis nunc eget lorem dolor sed.

Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Velit dignissim sodales ut eu sem. Magna fringilla urna porttitor rhoncus dolor purus non. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Rhoncus est pellentesque elit ullamcorper dignissim cras. Neque vitae tempus quam pellentesque nec nam aliquam sem. Eget nullam non nisi est. Nunc mi ipsum faucibus vitae aliquet. Nunc eget lorem dolor sed viverra. Varius sit amet mattis vulputate enim nulla aliquet. Velit scelerisque in dictum non consectetur a. Nulla pharetra diam sit amet. Orci phasellus egestas tellus rutrum tellus pellentesque.

Faucibus purus in massa tempor nec. Placerat in egestas erat imperdiet sed euismod nisi. Aliquam sem fringilla ut morbi. Rhoncus aenean vel elit scelerisque mauris pellentesque. Viverra nam libero justo laoreet sit amet. In fermentum posuere urna nec. Est ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Iaculis at erat pellentesque adipiscing. Turpis nunc eget lorem dolor sed. Ut placerat orci nulla pellentesque. Dolor magna eget est lorem ipsum. Mi quis hendrerit dolor magna eget. Blandit aliquam etiam erat velit. Vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra. Pharetra magna ac placerat vestibulum lectus. Massa tincidunt dui ut ornare lectus sit amet.

In cursus turpis massa tincidunt. Netus et malesuada fames ac turpis egestas. Duis ultricies lacus sed turpis. Tellus orci ac auctor augue mauris augue neque. In nibh mauris cursus mattis molestie a iaculis at erat. Hac habitasse platea dictumst quisque sagittis purus sit amet. Imperdiet dui accumsan sit amet nulla facilisi. Sit amet mattis vulputate enim nulla aliquet porttitor. Sed augue lacus viverra vitae congue. Eget gravida cum sociis natoque penatibus et magnis. Eu facilisis sed odio morbi quis commodo odio. Nec tincidunt praesent semper feugiat nibh. Nunc consequat interdum varius sit amet mattis. At elementum eu facilisis sed odio morbi. Magna eget est lorem ipsum dolor sit. Tincidunt nunc pulvinar sapien et. Turpis in eu mi bibendum neque egestas. Maecenas pharetra convallis posuere morbi leo urna molestie at. Vitae tempus quam pellentesque nec.

Diam vulputate ut pharetra sit amet aliquam id diam maecenas. Urna neque viverra justo nec ultrices dui. Lacus luctus accumsan tortor posuere. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Velit egestas dui id ornare arcu. Pulvinar neque laoreet suspendisse interdum. At erat pellentesque adipiscing commodo elit. Tristique magna sit amet purus gravida quis blandit turpis. Egestas diam in arcu cursus euismod quis viverra. Sit amet nisl suscipit adipiscing bibendum.

Adipiscing vitae proin sagittis nisl rhoncus. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Maecenas accumsan lacus vel facilisis volutpat. Cursus mattis molestie a iaculis at. Eu consequat ac felis donec et. Aliquam sem fringilla ut morbi tincidunt. Commodo sed egestas egestas fringilla phasellus. Lectus nulla at volutpat diam. Semper viverra nam libero justo laoreet sit. Cras adipiscing enim eu turpis egestas pretium aenean. Cursus sit amet dictum sit amet. Amet aliquam id diam maecenas ultricies mi eget mauris. Urna duis convallis convallis tellus id interdum velit. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Praesent elementum facilisis leo vel fringilla est ullamcorper. Eget duis at tellus at urna condimentum. Nisl tincidunt eget nullam non nisi est sit. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et.

Nibh cras pulvinar mattis nunc sed blandit libero. Sed sed risus pretium quam vulputate dignissim. Habitant morbi tristique senectus et netus et. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Ultrices eros in cursus turpis massa. Pellentesque habitant morbi tristique senectus et netus et malesuada. Condimentum mattis pellentesque id nibh tortor. Felis eget velit aliquet sagittis id consectetur purus. Sed felis eget velit aliquet sagittis id. Feugiat vivamus at augue eget arcu dictum varius. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit. Nec feugiat in fermentum posuere urna nec. Eget mauris pharetra et ultrices neque ornare aenean. Neque vitae tempus quam pellentesque nec nam aliquam sem.

Vitae auctor eu augue ut lectus. Vulputate dignissim suspendisse in est ante in nibh mauris cursus. Quis varius quam quisque id diam. Amet aliquam id diam maecenas ultricies mi eget mauris. Adipiscing bibendum est ultricies integer quis. Porta nibh venenatis cras sed. Lobortis elementum nibh tellus molestie nunc non blandit. Placerat in egestas erat imperdiet sed euismod. Tortor posuere ac ut consequat semper viverra. Ac turpis egestas sed tempus. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Massa tempor nec feugiat nisl pretium fusce id. Molestie a iaculis at erat. Placerat orci nulla pellentesque dignissim enim sit amet venenatis.

Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Neque viverra justo nec ultrices dui sapien. Ipsum dolor sit amet consectetur adipiscing. Ultricies lacus sed turpis tincidunt id aliquet. Sodales neque sodales ut etiam sit. Nibh nisl condimentum id venenatis a condimentum. Metus aliquam eleifend mi in nulla posuere sollicitudin. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Purus sit amet luctus venenatis lectus magna. Suspendisse in est ante in nibh mauris. Eget lorem dolor sed viverra ipsum. Tellus elementum sagittis vitae et leo duis ut.

Venenatis lectus magna fringilla urna porttitor rhoncus. Non sodales neque sodales ut etiam. Pellentesque elit eget gravida cum sociis. Donec et odio pellentesque diam volutpat commodo. Ac odio tempor orci dapibus ultrices in iaculis nunc. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel. Facilisis gravida neque convallis a cras semper auctor neque. Varius morbi enim nunc faucibus a pellentesque. Libero justo laoreet sit amet cursus. At volutpat diam ut venenatis tellus in metus. Nulla facilisi cras fermentum odio eu feugiat pretium nibh. Est pellentesque elit ullamcorper dignissim. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Ornare arcu odio ut sem. Nunc faucibus a pellentesque sit amet porttitor. Augue mauris augue neque gravida in fermentum et sollicitudin. Mauris in aliquam sem fringilla ut morbi. Ut sem nulla pharetra diam sit amet. Sit amet dictum sit amet justo donec enim diam vulputate. Augue interdum velit euismod in pellentesque massa placerat duis ultricies.

Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Lorem ipsum dolor sit amet consectetur adipiscing elit. Id diam vel quam elementum pulvinar. Euismod lacinia at quis risus sed vulputate odio. Vel fringilla est ullamcorper eget nulla facilisi. Massa sapien faucibus et molestie ac feugiat. Porttitor rhoncus dolor purus non enim praesent. Velit egestas dui id ornare arcu odio ut. Cras semper auctor neque vitae tempus quam. Leo urna molestie at elementum. Vitae semper quis lectus nulla at volutpat diam. Justo eget magna fermentum iaculis eu non diam. Adipiscing bibendum est ultricies integer quis auctor. Nullam eget felis eget nunc lobortis. Et malesuada fames ac turpis. Ac felis donec et odio pellentesque diam volutpat. Mattis enim ut tellus elementum sagittis vitae. Mauris augue neque gravida in fermentum et. Placerat in egestas erat imperdiet sed euismod nisi.

Congue nisi vitae suscipit tellus mauris a. Egestas purus viverra accumsan in. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. A lacus vestibulum sed arcu non odio euismod. Non consectetur a erat nam at lectus. Pretium viverra suspendisse potenti nullam ac. Nullam eget felis eget nunc lobortis mattis aliquam. Ultrices eros in cursus turpis massa. Vestibulum morbi blandit cursus risus at. Volutpat maecenas volutpat blandit aliquam etiam. Eu non diam phasellus vestibulum lorem sed risus. Nam libero justo laoreet sit amet cursus sit. Libero enim sed faucibus turpis in eu. Mollis aliquam ut porttitor leo a diam. Tincidunt eget nullam non nisi. A diam sollicitudin tempor id eu nisl. Dignissim enim sit amet venenatis urna cursus eget.

Laoreet suspendisse interdum consectetur libero id. Eleifend donec pretium vulputate sapien nec sagittis. Vel quam elementum pulvinar etiam. Pellentesque habitant morbi tristique senectus et netus. Velit ut tortor pretium viverra suspendisse. Facilisi morbi tempus iaculis urna id volutpat. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Lacus vel facilisis volutpat est velit egestas dui. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Non diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Neque volutpat ac tincidunt vitae semper quis lectus. Turpis massa sed elementum tempus egestas sed sed. Vel pharetra vel turpis nunc eget lorem. Rhoncus est pellentesque elit ullamcorper dignissim cras. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Urna duis convallis convallis tellus id interdum velit laoreet id. Netus et malesuada fames ac turpis egestas maecenas pharetra. Scelerisque purus semper eget duis at tellus at.

Id consectetur purus ut faucibus pulvinar elementum integer enim. Et netus et malesuada fames ac turpis. Consectetur a erat nam at lectus urna. Congue eu consequat ac felis donec et odio pellentesque diam. Adipiscing tristique risus nec feugiat in fermentum. In fermentum et sollicitudin ac. Sed libero enim sed faucibus. Elit duis tristique sollicitudin nibh. Et netus et malesuada fames ac. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. In pellentesque massa placerat duis ultricies lacus sed. Cursus in hac habitasse platea. In egestas erat imperdiet sed euismod nisi. Enim nec dui nunc mattis enim. Aliquet eget sit amet tellus cras adipiscing enim eu. Suspendisse in est ante in nibh mauris cursus mattis molestie. Rhoncus est pellentesque elit ullamcorper dignissim. Sem integer vitae justo eget magna fermentum iaculis eu.

Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Dictum varius duis at consectetur lorem donec massa. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Mattis molestie a iaculis at erat. Morbi tristique senectus et netus. Convallis tellus id interdum velit laoreet id donec ultrices tincidunt. Vestibulum sed arcu non odio euismod. Nunc sed id semper risus in hendrerit gravida. Vitae semper quis lectus nulla at volutpat. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Odio ut sem nulla pharetra diam. Nunc sed augue lacus viverra vitae congue. Ultricies mi quis hendrerit dolor magna eget. Interdum velit laoreet id donec ultrices. Arcu risus quis varius quam quisque id diam vel. Quis commodo odio aenean sed adipiscing diam. In ornare quam viverra orci sagittis eu volutpat odio. Enim eu turpis egestas pretium aenean pharetra. Scelerisque fermentum dui faucibus in ornare quam. Fringilla phasellus faucibus scelerisque eleifend.

Aliquet sagittis id consectetur purus ut faucibus pulvinar. Augue lacus viverra vitae congue. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Dictumst quisque sagittis purus sit amet volutpat consequat. Nisl pretium fusce id velit ut tortor pretium. Vivamus at augue eget arcu dictum. Pretium fusce id velit ut. Lacus laoreet non curabitur gravida arcu ac. Feugiat sed lectus vestibulum mattis ullamcorper velit. Aenean pharetra magna ac placerat vestibulum lectus. Purus sit amet luctus venenatis. Vel quam elementum pulvinar etiam. Arcu dictum varius duis at. A arcu cursus vitae congue mauris rhoncus. Sed id semper risus in hendrerit gravida rutrum. Eu sem integer vitae justo eget magna fermentum iaculis. Vitae purus faucibus ornare suspendisse.

Sed faucibus turpis in eu. Est ante in nibh mauris cursus mattis molestie a iaculis. Elit at imperdiet dui accumsan sit amet nulla. Purus in mollis nunc sed id semper risus. Tempor orci dapibus ultrices in. Malesuada fames ac turpis egestas. Nunc sed blandit libero volutpat sed cras ornare. Sit amet aliquam id diam maecenas ultricies mi. Orci porta non pulvinar neque laoreet. Vitae turpis massa sed elementum tempus egestas sed sed. Nisl nisi scelerisque eu ultrices. Hac habitasse platea dictumst vestibulum rhoncus. Lacus vestibulum sed arcu non odio euismod. Senectus et netus et malesuada fames ac turpis. In nibh mauris cursus mattis molestie a iaculis. Eu sem integer vitae justo. Leo vel fringilla est ullamcorper eget. Maecenas sed enim ut sem viverra.

Sapien nec sagittis aliquam malesuada bibendum. Lobortis mattis aliquam faucibus purus in massa tempor. Et malesuada fames ac turpis. Lorem ipsum dolor sit amet consectetur. Dui id ornare arcu odio. Sed velit dignissim sodales ut eu sem integer vitae. Libero justo laoreet sit amet cursus sit amet. Auctor urna nunc id cursus metus aliquam eleifend. Consequat nisl vel pretium lectus quam id leo in. Tristique risus nec feugiat in fermentum posuere urna nec tincidunt. Hendrerit gravida rutrum quisque non tellus orci ac auctor. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Magna sit amet purus gravida quis blandit turpis cursus in. Hac habitasse platea dictumst quisque sagittis purus. Nulla posuere sollicitudin aliquam ultrices sagittis orci a.

Id porta nibh venenatis cras sed felis eget. Eu scelerisque felis imperdiet proin fermentum leo vel. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. A lacus vestibulum sed arcu non odio. Venenatis urna cursus eget nunc scelerisque viverra. Ultrices dui sapien eget mi proin sed. A diam maecenas sed enim ut sem viverra aliquet eget. Risus sed vulputate odio ut enim blandit volutpat. Enim facilisis gravida neque convallis a cras. Consectetur a erat nam at lectus urna duis. A condimentum vitae sapien pellentesque habitant morbi tristique. Hendrerit dolor magna eget est lorem. Integer enim neque volutpat ac tincidunt vitae semper quis. Eget aliquet nibh praesent tristique magna sit amet purus gravida. Malesuada nunc vel risus commodo. A diam maecenas sed enim ut sem. Mauris sit amet massa vitae.

Est sit amet facilisis magna etiam. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. In cursus turpis massa tincidunt dui. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Nunc id cursus metus aliquam eleifend mi. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Ornare suspendisse sed nisi lacus. Porttitor massa id neque aliquam vestibulum. Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus.

Vitae proin sagittis nisl rhoncus. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Tortor posuere ac ut consequat semper viverra. Enim eu turpis egestas pretium aenean pharetra magna ac placerat. Nisl suscipit adipiscing bibendum est ultricies integer. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Ultricies leo integer malesuada nunc vel risus commodo. Est pellentesque elit ullamcorper dignissim cras tincidunt. Nisl nisi scelerisque eu ultrices vitae auctor eu. Fermentum leo vel orci porta non pulvinar neque. Eget nullam non nisi est sit amet facilisis magna etiam. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Eu volutpat odio facilisis mauris. Eu augue ut lectus arcu bibendum at. Ut tristique et egestas quis ipsum suspendisse. Ut eu sem integer vitae justo eget magna fermentum. Nibh mauris cursus mattis molestie a iaculis at. Eu ultrices vitae auctor eu augue ut lectus arcu. Tellus elementum sagittis vitae et leo duis ut diam quam.

Quis eleifend quam adipiscing vitae. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Platea dictumst quisque sagittis purus sit amet. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Ut consequat semper viverra nam libero justo laoreet. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Dictum non consectetur a erat nam at. Pretium quam vulputate dignissim suspendisse. Adipiscing elit duis tristique sollicitudin nibh. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Ac orci phasellus egestas tellus rutrum tellus. Lacus sed turpis tincidunt id aliquet.

Netus et malesuada fames ac. Lacus sed turpis tincidunt id aliquet. Ipsum dolor sit amet consectetur adipiscing elit. Ultrices tincidunt arcu non sodales neque sodales. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Elementum integer enim neque volutpat ac tincidunt vitae. Nec feugiat nisl pretium fusce id. Est placerat in egestas erat imperdiet sed euismod nisi porta. Sagittis orci a scelerisque purus semper eget duis at tellus. Sed faucibus turpis in eu mi. Feugiat sed lectus vestibulum mattis ullamcorper. Congue quisque egestas diam in arcu cursus.

Dapibus ultrices in iaculis nunc sed augue. Tincidunt augue interdum velit euismod in. Aliquam purus sit amet luctus venenatis lectus magna fringilla urna. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Pellentesque pulvinar pellentesque habitant morbi tristique. Donec massa sapien faucibus et molestie ac feugiat sed. Commodo quis imperdiet massa tincidunt nunc pulvinar. Mi eget mauris pharetra et ultrices. Ipsum dolor sit amet consectetur adipiscing elit. Faucibus purus in massa tempor. Urna neque viverra justo nec ultrices dui sapien eget mi. Elit ut aliquam purus sit. Tristique risus nec feugiat in fermentum posuere urna nec tincidunt. Diam vel quam elementum pulvinar etiam non quam. Praesent elementum facilisis leo vel. Eget gravida cum sociis natoque penatibus et magnis dis. Egestas pretium aenean pharetra magna ac placerat vestibulum. Magnis dis parturient montes nascetur ridiculus mus mauris.

Hac habitasse platea dictumst vestibulum rhoncus. Cursus metus aliquam eleifend mi in nulla posuere. In tellus integer feugiat scelerisque. Pellentesque massa placerat duis ultricies lacus sed turpis. Porttitor leo a diam sollicitudin tempor id eu nisl nunc. Placerat in egestas erat imperdiet. Ullamcorper sit amet risus nullam eget felis eget nunc lobortis. Enim sed faucibus turpis in eu mi bibendum. Gravida cum sociis natoque penatibus et magnis dis parturient. Quam quisque id diam vel quam elementum pulvinar. Arcu vitae elementum curabitur vitae. Egestas purus viverra accumsan in. Nisi lacus sed viverra tellus in hac. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Faucibus vitae aliquet nec ullamcorper. Leo urna molestie at elementum eu. Congue mauris rhoncus aenean vel elit scelerisque mauris. Lectus urna duis convallis convallis. In metus vulputate eu scelerisque felis imperdiet proin fermentum.

Enim sit amet venenatis urna cursus eget nunc scelerisque. Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. Nam aliquam sem et tortor. Praesent elementum facilisis leo vel. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Interdum velit euismod in pellentesque massa placerat duis ultricies lacus. Consequat id porta nibh venenatis cras sed. Eget mauris pharetra et ultrices neque ornare aenean. Et leo duis ut diam. Aliquam ultrices sagittis orci a scelerisque.

Ac felis donec et odio pellentesque diam volutpat. Nullam ac tortor vitae purus faucibus ornare. Fermentum et sollicitudin ac orci phasellus. Ut lectus arcu bibendum at varius. Sed risus pretium quam vulputate. Non curabitur gravida arcu ac. Sit amet consectetur adipiscing elit ut aliquam purus sit. Pellentesque elit eget gravida cum sociis natoque penatibus et. Erat pellentesque adipiscing commodo elit at imperdiet dui. Facilisis sed odio morbi quis commodo. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Posuere urna nec tincidunt praesent semper feugiat nibh. Quisque non tellus orci ac auctor augue mauris augue. Vestibulum morbi blandit cursus risus. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Nisl purus in mollis nunc. Amet mauris commodo quis imperdiet massa tincidunt. Viverra mauris in aliquam sem fringilla ut morbi.

Donec pretium vulputate sapien nec. Morbi tristique senectus et netus et malesuada fames ac. Mollis nunc sed id semper risus. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Volutpat ac tincidunt vitae semper. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Euismod lacinia at quis risus sed. Ut sem viverra aliquet eget sit. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Feugiat nisl pretium fusce id velit ut tortor pretium. Volutpat odio facilisis mauris sit amet massa. Dolor purus non enim praesent elementum facilisis. Facilisis leo vel fringilla est. Nunc mattis enim ut tellus.

Augue neque gravida in fermentum et sollicitudin. Commodo ullamcorper a lacus vestibulum. Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Tortor dignissim convallis aenean et tortor. Tellus pellentesque eu tincidunt tortor aliquam. Etiam sit amet nisl purus in mollis nunc sed id. Viverra nam libero justo laoreet sit amet. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. At quis risus sed vulputate odio ut enim blandit volutpat. Faucibus pulvinar elementum integer enim neque volutpat ac. Id cursus metus aliquam eleifend mi in. Nulla pharetra diam sit amet nisl suscipit. Et netus et malesuada fames ac turpis egestas maecenas pharetra. Amet aliquam id diam maecenas. Semper quis lectus nulla at. Sed ullamcorper morbi tincidunt ornare massa eget.

Elementum sagittis vitae et leo duis ut diam. Ut tellus elementum sagittis vitae et. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Massa enim nec dui nunc mattis enim ut. Nulla facilisi etiam dignissim diam. Risus quis varius quam quisque id. Nunc id cursus metus aliquam eleifend mi in nulla posuere. Convallis tellus id interdum velit laoreet id donec ultrices. Et malesuada fames ac turpis egestas. Libero enim sed faucibus turpis in eu mi bibendum neque. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Platea dictumst vestibulum rhoncus est pellentesque.

Viverra suspendisse potenti nullam ac tortor vitae. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Id neque aliquam vestibulum morbi blandit cursus risus. Sed enim ut sem viverra aliquet eget sit amet tellus. Rhoncus aenean vel elit scelerisque. Sollicitudin tempor id eu nisl. Nisi scelerisque eu ultrices vitae auctor eu augue ut. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. At tempor commodo ullamcorper a lacus. Vitae auctor eu augue ut lectus arcu. In ornare quam viverra orci.

Gravida arcu ac tortor dignissim convallis aenean et tortor at. Eu lobortis elementum nibh tellus molestie nunc non. Sed blandit libero volutpat sed cras ornare arcu dui vivamus. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Facilisis mauris sit amet massa. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Ac tincidunt vitae semper quis lectus nulla at. Leo vel fringilla est ullamcorper. Tellus mauris a diam maecenas sed enim ut. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Ornare massa eget egestas purus viverra accumsan in nisl nisi. Laoreet sit amet cursus sit amet. Congue eu consequat ac felis donec et odio.

Elementum nisi quis eleifend quam adipiscing. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Cursus turpis massa tincidunt dui ut. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Elit eget gravida cum sociis natoque. Sollicitudin nibh sit amet commodo nulla facilisi. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Eu mi bibendum neque egestas congue quisque egestas. Mattis ullamcorper velit sed ullamcorper morbi tincidunt. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Vivamus at augue eget arcu dictum varius duis. Semper feugiat nibh sed pulvinar proin gravida.

Sed elementum tempus egestas sed sed. Dolor purus non enim praesent elementum. At imperdiet dui accumsan sit amet nulla. Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Pulvinar pellentesque habitant morbi tristique senectus et netus. Interdum consectetur libero id faucibus nisl. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Senectus et netus et malesuada fames ac. Varius morbi enim nunc faucibus a. Ac turpis egestas sed tempus urna et pharetra pharetra massa. Euismod elementum nisi quis eleifend quam. Rutrum quisque non tellus orci ac auctor augue. Condimentum mattis pellentesque id nibh tortor id aliquet. Accumsan tortor posuere ac ut consequat. Rhoncus dolor purus non enim praesent. Ac tortor vitae purus faucibus ornare. Risus in hendrerit gravida rutrum quisque non tellus. Maecenas accumsan lacus vel facilisis.

Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Diam vel quam elementum pulvinar etiam non quam lacus suspendisse. Et leo duis ut diam quam nulla porttitor. Neque convallis a cras semper auctor neque vitae tempus. Egestas purus viverra accumsan in nisl nisi scelerisque. Mattis enim ut tellus elementum sagittis. Scelerisque purus semper eget duis at tellus at urna. Lectus proin nibh nisl condimentum id venenatis. Egestas diam in arcu cursus. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus.

Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Maecenas ultricies mi eget mauris pharetra et ultrices. Scelerisque in dictum non consectetur a erat. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Enim ut sem viverra aliquet eget sit amet tellus. Mi in nulla posuere sollicitudin. Non enim praesent elementum facilisis leo vel fringilla. Consectetur a erat nam at lectus urna duis convallis convallis. Pellentesque habitant morbi tristique senectus et netus et malesuada. Elit ut aliquam purus sit amet luctus venenatis lectus. Vitae tortor condimentum lacinia quis vel eros donec ac. Faucibus ornare suspendisse sed nisi lacus sed viverra. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Vitae semper quis lectus nulla at.

Augue interdum velit euismod in. Senectus et netus et malesuada. Augue neque gravida in fermentum et sollicitudin ac orci. Sollicitudin aliquam ultrices sagittis orci a. Pulvinar pellentesque habitant morbi tristique senectus et. Velit egestas dui id ornare arcu odio ut sem. Risus sed vulputate odio ut. Pulvinar neque laoreet suspendisse interdum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Cras sed felis eget velit aliquet. Dolor magna eget est lorem. Sit amet volutpat consequat mauris nunc congue nisi.

Eu lobortis elementum nibh tellus molestie nunc non blandit. Vitae purus faucibus ornare suspendisse sed nisi lacus. Diam sit amet nisl suscipit. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Lacus laoreet non curabitur gravida arcu ac. Et leo duis ut diam quam nulla. Et ultrices neque ornare aenean. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. In arcu cursus euismod quis viverra nibh. Volutpat blandit aliquam etiam erat. Ultricies leo integer malesuada nunc vel risus. Sed egestas egestas fringilla phasellus faucibus. Tellus cras adipiscing enim eu turpis. Orci dapibus ultrices in iaculis nunc sed.

Platea dictumst quisque sagittis purus sit amet volutpat. Odio tempor orci dapibus ultrices in iaculis nunc sed. Nisi vitae suscipit tellus mauris. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Arcu bibendum at varius vel pharetra vel. Gravida in fermentum et sollicitudin ac. Sed viverra ipsum nunc aliquet bibendum enim facilisis. Risus at ultrices mi tempus imperdiet nulla malesuada. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Ac odio tempor orci dapibus ultrices in. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Enim facilisis gravida neque convallis a cras semper auctor. In hac habitasse platea dictumst.

Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Viverra tellus in hac habitasse platea dictumst vestibulum. Semper auctor neque vitae tempus. Risus quis varius quam quisque id diam vel. Faucibus et molestie ac feugiat sed lectus vestibulum. Turpis egestas integer eget aliquet nibh praesent. Consequat id porta nibh venenatis cras. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Ultricies integer quis auctor elit sed vulputate mi. Facilisi morbi tempus iaculis urna id volutpat. Eros donec ac odio tempor orci dapibus ultrices. Ac tortor dignissim convallis aenean. Enim ut sem viverra aliquet eget sit amet tellus. Tincidunt eget nullam non nisi est sit amet facilisis magna. Turpis egestas integer eget aliquet nibh praesent. Vitae congue mauris rhoncus aenean vel elit.

Lacus vel facilisis volutpat est. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Senectus et netus et malesuada fames ac turpis egestas. Sed augue lacus viverra vitae congue eu consequat ac felis. Neque viverra justo nec ultrices dui. In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Accumsan sit amet nulla facilisi morbi. Enim ut sem viverra aliquet eget sit. Nulla pellentesque dignissim enim sit amet. Sed turpis tincidunt id aliquet risus feugiat in. Tincidunt praesent semper feugiat nibh. Blandit turpis cursus in hac habitasse platea dictumst. Vivamus arcu felis bibendum ut tristique et egestas quis. Vulputate ut pharetra sit amet aliquam id. Nisl vel pretium lectus quam id leo. Libero enim sed faucibus turpis in. Eu augue ut lectus arcu bibendum at varius vel pharetra.

Volutpat diam ut venenatis tellus in. Condimentum mattis pellentesque id nibh tortor id. Non quam lacus suspendisse faucibus. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Tristique senectus et netus et. Blandit turpis cursus in hac habitasse. Proin nibh nisl condimentum id venenatis a. Cursus eget nunc scelerisque viverra. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Facilisi morbi tempus iaculis urna. Pharetra magna ac placerat vestibulum. Leo a diam sollicitudin tempor id eu nisl. Tortor pretium viverra suspendisse potenti.

Amet venenatis urna cursus eget nunc scelerisque viverra. Dui ut ornare lectus sit amet est. Condimentum mattis pellentesque id nibh tortor id aliquet. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Aenean euismod elementum nisi quis eleifend. Sem et tortor consequat id. Sit amet consectetur adipiscing elit ut aliquam. Sagittis nisl rhoncus mattis rhoncus. Sagittis orci a scelerisque purus semper eget duis. Integer quis auctor elit sed vulputate. Risus quis varius quam quisque id diam vel quam elementum. Odio ut enim blandit volutpat maecenas. Molestie nunc non blandit massa enim nec dui nunc mattis. Quis varius quam quisque id. Nisl rhoncus mattis rhoncus urna. Fermentum dui faucibus in ornare. In hac habitasse platea dictumst vestibulum rhoncus. Semper eget duis at tellus at urna condimentum mattis. Varius duis at consectetur lorem donec. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi.

Tellus cras adipiscing enim eu turpis egestas. Morbi non arcu risus quis varius quam. Facilisis gravida neque convallis a cras. Fermentum dui faucibus in ornare. Eu sem integer vitae justo. Sed euismod nisi porta lorem mollis aliquam ut porttitor. Nunc lobortis mattis aliquam faucibus purus in massa. Sem nulla pharetra diam sit. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Fermentum et sollicitudin ac orci.

Nisl nunc mi ipsum faucibus vitae. Lectus sit amet est placerat in egestas erat imperdiet sed. Blandit massa enim nec dui nunc. Sit amet tellus cras adipiscing enim eu turpis. Nunc vel risus commodo viverra maecenas. Tincidunt vitae semper quis lectus nulla at. Id velit ut tortor pretium viverra. Lacinia quis vel eros donec ac. Orci sagittis eu volutpat odio facilisis mauris. Ipsum faucibus vitae aliquet nec.

Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Nulla pellentesque dignissim enim sit amet venenatis. Dolor morbi non arcu risus quis varius quam quisque. Maecenas accumsan lacus vel facilisis volutpat est velit. Nec ultrices dui sapien eget mi proin sed libero enim. Auctor eu augue ut lectus arcu bibendum. Id semper risus in hendrerit gravida. Dolor sit amet consectetur adipiscing elit duis tristique. Mauris ultrices eros in cursus turpis massa tincidunt dui. Neque gravida in fermentum et. Orci sagittis eu volutpat odio facilisis. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Adipiscing enim eu turpis egestas. Accumsan tortor posuere ac ut consequat semper. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Morbi tempus iaculis urna id volutpat lacus laoreet. Aliquam sem et tortor consequat id porta.

Lacinia at quis risus sed vulputate odio ut enim blandit. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Tortor dignissim convallis aenean et tortor. Pellentesque habitant morbi tristique senectus et netus. Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Arcu non sodales neque sodales ut. Dolor sed viverra ipsum nunc aliquet bibendum enim. Leo urna molestie at elementum. Iaculis nunc sed augue lacus viverra. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin.

Elementum sagittis vitae et leo. Urna duis convallis convallis tellus id interdum velit laoreet id. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. In mollis nunc sed id semper risus. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Ut pharetra sit amet aliquam id diam maecenas. Ac turpis egestas sed tempus urna et pharetra pharetra. Ipsum dolor sit amet consectetur. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper.

Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a. Risus ultricies tristique nulla aliquet enim tortor at auctor. A arcu cursus vitae congue mauris rhoncus aenean. Vitae aliquet nec ullamcorper sit amet risus. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Morbi non arcu risus quis varius. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Non pulvinar neque laoreet suspendisse interdum. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Feugiat in ante metus dictum at tempor. Maecenas ultricies mi eget mauris. Mauris in aliquam sem fringilla ut morbi tincidunt augue interdum. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Egestas sed tempus urna et pharetra pharetra massa massa. Et netus et malesuada fames ac turpis egestas. Arcu ac tortor dignissim convallis aenean et tortor. Sed viverra ipsum nunc aliquet. Ut sem nulla pharetra diam. Eu mi bibendum neque egestas congue quisque egestas.

Mauris augue neque gravida in fermentum et sollicitudin ac orci. Nibh sit amet commodo nulla facilisi nullam. Consectetur lorem donec massa sapien faucibus. In fermentum et sollicitudin ac orci phasellus. Lectus quam id leo in vitae turpis massa sed. Consequat semper viverra nam libero. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Ultricies leo integer malesuada nunc. Natoque penatibus et magnis dis parturient. Sit amet cursus sit amet. Commodo odio aenean sed adipiscing diam. Ipsum consequat nisl vel pretium lectus quam id. Pulvinar pellentesque habitant morbi tristique. Aliquet enim tortor at auctor urna nunc id cursus. Viverra justo nec ultrices dui sapien eget mi.

Elit ullamcorper dignissim cras tincidunt. Non enim praesent elementum facilisis leo vel fringilla est. Tristique sollicitudin nibh sit amet commodo. Lectus mauris ultrices eros in cursus turpis massa. Nibh tellus molestie nunc non blandit. Amet est placerat in egestas erat imperdiet. Adipiscing enim eu turpis egestas pretium aenean pharetra magna. Lacus sed viverra tellus in. Pulvinar etiam non quam lacus. Mattis ullamcorper velit sed ullamcorper. Venenatis urna cursus eget nunc scelerisque. A pellentesque sit amet porttitor eget dolor morbi non arcu. Vestibulum lectus mauris ultrices eros. Pellentesque nec nam aliquam sem et tortor consequat. Auctor eu augue ut lectus arcu bibendum at varius. Eu tincidunt tortor aliquam nulla. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. A iaculis at erat pellentesque adipiscing commodo elit. Egestas fringilla phasellus faucibus scelerisque.

Sollicitudin tempor id eu nisl nunc mi. Viverra vitae congue eu consequat ac. Potenti nullam ac tortor vitae. Accumsan in nisl nisi scelerisque eu ultrices vitae. A cras semper auctor neque vitae tempus quam pellentesque nec. Vitae semper quis lectus nulla at volutpat diam. Id diam vel quam elementum. Vivamus arcu felis bibendum ut tristique et egestas quis. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Nam libero justo laoreet sit amet cursus.

Amet commodo nulla facilisi nullam. Elementum eu facilisis sed odio morbi quis commodo odio aenean. A arcu cursus vitae congue mauris. Dolor sed viverra ipsum nunc. Imperdiet massa tincidunt nunc pulvinar sapien. Mauris augue neque gravida in fermentum et sollicitudin ac. Risus nullam eget felis eget nunc lobortis. In iaculis nunc sed augue lacus. Pellentesque diam volutpat commodo sed egestas egestas. Aliquet lectus proin nibh nisl condimentum id venenatis. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Nisl nunc mi ipsum faucibus vitae aliquet. Vel quam elementum pulvinar etiam non. Purus in mollis nunc sed id semper. Ultrices in iaculis nunc sed augue lacus. Tempus quam pellentesque nec nam.

Sed viverra ipsum nunc aliquet bibendum enim. Risus nec feugiat in fermentum posuere urna. Mauris nunc congue nisi vitae. Arcu cursus euismod quis viverra nibh cras pulvinar. Est velit egestas dui id ornare arcu. Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Dui sapien eget mi proin sed. Fames ac turpis egestas maecenas pharetra convallis posuere morbi. Cursus in hac habitasse platea dictumst quisque sagittis. Eget magna fermentum iaculis eu non. Consequat nisl vel pretium lectus quam id leo. Non arcu risus quis varius quam quisque id. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Amet nisl purus in mollis nunc sed id semper. Euismod lacinia at quis risus sed vulputate odio ut enim.

Lacus viverra vitae congue eu consequat ac felis donec et. Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Interdum posuere lorem ipsum dolor. Consequat semper viverra nam libero justo laoreet sit. Purus viverra accumsan in nisl nisi scelerisque eu. Ipsum suspendisse ultrices gravida dictum fusce ut. Porta lorem mollis aliquam ut. Dignissim enim sit amet venenatis urna cursus. Eget nullam non nisi est sit amet. Ornare quam viverra orci sagittis eu volutpat odio. Ut pharetra sit amet aliquam id diam maecenas ultricies mi. Tristique sollicitudin nibh sit amet commodo. Vestibulum morbi blandit cursus risus at ultrices mi. Maecenas sed enim ut sem viverra aliquet eget sit amet. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Dui id ornare arcu odio.

Fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Venenatis lectus magna fringilla urna porttitor. Habitant morbi tristique senectus et. Urna duis convallis convallis tellus id interdum velit. Justo eget magna fermentum iaculis eu non diam. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Orci porta non pulvinar neque. Eget gravida cum sociis natoque penatibus. Tellus orci ac auctor augue mauris augue neque. Nulla pharetra diam sit amet nisl suscipit adipiscing. Fames ac turpis egestas integer eget aliquet nibh. In cursus turpis massa tincidunt dui ut ornare. At consectetur lorem donec massa sapien faucibus. Blandit aliquam etiam erat velit.

Urna id volutpat lacus laoreet non curabitur gravida. Id venenatis a condimentum vitae sapien pellentesque. Amet mattis vulputate enim nulla aliquet porttitor lacus. Amet dictum sit amet justo donec enim diam vulputate. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Scelerisque in dictum non consectetur. Nisi vitae suscipit tellus mauris a diam maecenas sed. Facilisi cras fermentum odio eu feugiat pretium nibh. Risus quis varius quam quisque id diam vel quam elementum. Odio ut enim blandit volutpat maecenas volutpat blandit. Bibendum at varius vel pharetra vel turpis. Nullam eget felis eget nunc lobortis mattis. Venenatis cras sed felis eget velit aliquet. Leo in vitae turpis massa. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Tortor condimentum lacinia quis vel eros donec ac odio tempor.

Vitae turpis massa sed elementum tempus egestas sed. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Id interdum velit laoreet id donec ultrices. Maecenas pharetra convallis posuere morbi leo urna molestie. Pulvinar etiam non quam lacus suspendisse. Massa ultricies mi quis hendrerit dolor magna eget. Et malesuada fames ac turpis egestas. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Nisl condimentum id venenatis a. Nisl vel pretium lectus quam. Felis donec et odio pellentesque.

In fermentum et sollicitudin ac orci phasellus. Orci a scelerisque purus semper eget duis at tellus. Velit laoreet id donec ultrices tincidunt arcu. Consectetur purus ut faucibus pulvinar elementum integer enim. Massa sed elementum tempus egestas sed. Faucibus interdum posuere lorem ipsum dolor. Tempor nec feugiat nisl pretium fusce id velit ut. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Arcu non sodales neque sodales ut etiam sit amet. Risus nec feugiat in fermentum posuere urna nec.

Nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Congue mauris rhoncus aenean vel elit scelerisque. Pellentesque habitant morbi tristique senectus. Egestas integer eget aliquet nibh. Volutpat odio facilisis mauris sit amet. Urna duis convallis convallis tellus id interdum velit laoreet. Quis viverra nibh cras pulvinar mattis nunc sed. Sapien eget mi proin sed libero enim sed faucibus turpis. Eu tincidunt tortor aliquam nulla facilisi. Sed tempus urna et pharetra pharetra massa massa ultricies.

Ipsum dolor sit amet consectetur. Nunc vel risus commodo viverra maecenas. Pharetra vel turpis nunc eget lorem dolor. Mi proin sed libero enim sed faucibus. Lectus arcu bibendum at varius. Pretium nibh ipsum consequat nisl vel pretium. Nibh tellus molestie nunc non blandit massa enim. Tincidunt praesent semper feugiat nibh sed pulvinar proin. Eros donec ac odio tempor orci dapibus ultrices in. Eu feugiat pretium nibh ipsum consequat nisl vel. Enim nec dui nunc mattis enim. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Lectus mauris ultrices eros in cursus turpis massa tincidunt dui. Eget nulla facilisi etiam dignissim diam quis enim lobortis. Donec enim diam vulputate ut pharetra. At augue eget arcu dictum. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Ultrices in iaculis nunc sed.

Enim neque volutpat ac tincidunt. Adipiscing elit ut aliquam purus sit amet. Gravida rutrum quisque non tellus orci ac auctor augue. Molestie at elementum eu facilisis sed odio morbi quis commodo. Libero justo laoreet sit amet cursus sit amet dictum. Aliquet bibendum enim facilisis gravida neque convallis. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Ut placerat orci nulla pellentesque dignissim enim. Lacus sed viverra tellus in hac habitasse platea dictumst. Eget nunc scelerisque viverra mauris in aliquam. Neque egestas congue quisque egestas diam in. Vitae auctor eu augue ut lectus arcu bibendum.

Semper risus in hendrerit gravida rutrum quisque. Est ultricies integer quis auctor elit sed vulputate mi. At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Pellentesque habitant morbi tristique senectus et netus. Facilisis leo vel fringilla est. In tellus integer feugiat scelerisque. Leo vel orci porta non. Id cursus metus aliquam eleifend mi in nulla. Id aliquet lectus proin nibh nisl condimentum id venenatis. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor.

Arcu bibendum at varius vel pharetra vel turpis nunc. Nec feugiat in fermentum posuere urna nec tincidunt praesent semper. Mattis vulputate enim nulla aliquet. Gravida rutrum quisque non tellus orci ac auctor augue mauris. Tincidunt nunc pulvinar sapien et ligula ullamcorper. Ut pharetra sit amet aliquam id diam maecenas ultricies. Justo eget magna fermentum iaculis. Scelerisque in dictum non consectetur. Consectetur libero id faucibus nisl tincidunt eget nullam non. Nec sagittis aliquam malesuada bibendum.

Sapien pellentesque habitant morbi tristique senectus et netus. Ultricies leo integer malesuada nunc. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Ac turpis egestas maecenas pharetra convallis posuere morbi leo. Euismod elementum nisi quis eleifend quam. Duis convallis convallis tellus id interdum velit laoreet id donec. In tellus integer feugiat scelerisque varius morbi enim nunc. Lectus magna fringilla urna porttitor rhoncus dolor purus. Fringilla urna porttitor rhoncus dolor purus non. Risus pretium quam vulputate dignissim. Ut consequat semper viverra nam libero justo laoreet sit amet. Aliquam ut porttitor leo a diam. Risus commodo viverra maecenas accumsan lacus vel. Consequat nisl vel pretium lectus quam id leo in. Aliquam nulla facilisi cras fermentum odio. Non sodales neque sodales ut. Tincidunt eget nullam non nisi est sit amet facilisis magna. Euismod in pellentesque massa placerat duis ultricies lacus sed turpis.

Sit amet aliquam id diam maecenas ultricies. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Neque gravida in fermentum et sollicitudin ac orci. Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Enim sed faucibus turpis in eu mi. Gravida rutrum quisque non tellus orci ac auctor. Commodo sed egestas egestas fringilla phasellus. Fusce id velit ut tortor pretium. Gravida rutrum quisque non tellus orci ac. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Sapien pellentesque habitant morbi tristique. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum.

Hac habitasse platea dictumst vestibulum rhoncus. In mollis nunc sed id. Tristique nulla aliquet enim tortor at auctor urna. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. A scelerisque purus semper eget duis at tellus at. Scelerisque viverra mauris in aliquam sem. Netus et malesuada fames ac turpis egestas sed tempus. Id consectetur purus ut faucibus pulvinar elementum integer. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum.

Venenatis urna cursus eget nunc. Quis varius quam quisque id diam vel. Tincidunt lobortis feugiat vivamus at. Porttitor rhoncus dolor purus non enim. Semper feugiat nibh sed pulvinar proin gravida. Et malesuada fames ac turpis egestas maecenas pharetra. Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Sed tempus urna et pharetra pharetra. Diam maecenas ultricies mi eget mauris pharetra. Euismod elementum nisi quis eleifend quam. Ante in nibh mauris cursus. Tincidunt ornare massa eget egestas purus viverra accumsan in. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Eu consequat ac felis donec et odio. Et egestas quis ipsum suspendisse ultrices gravida. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Mauris augue neque gravida in fermentum. Sodales neque sodales ut etiam sit amet. Massa tempor nec feugiat nisl pretium fusce id velit. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque.

Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Pellentesque diam volutpat commodo sed egestas egestas fringilla. Auctor elit sed vulputate mi sit amet mauris. Auctor elit sed vulputate mi sit amet mauris commodo quis. Dolor sit amet consectetur adipiscing. Morbi tristique senectus et netus et malesuada fames ac turpis. Sit amet est placerat in egestas erat imperdiet sed. Nunc pulvinar sapien et ligula ullamcorper malesuada. Amet volutpat consequat mauris nunc congue. Nec nam aliquam sem et tortor consequat id porta. Sed nisi lacus sed viverra tellus in hac habitasse platea. Ut pharetra sit amet aliquam id diam. Sit amet porttitor eget dolor morbi non. Egestas sed tempus urna et. Eu augue ut lectus arcu bibendum at varius vel pharetra. Potenti nullam ac tortor vitae purus faucibus ornare. Eget gravida cum sociis natoque penatibus et.

Bibendum at varius vel pharetra vel turpis nunc eget. Id porta nibh venenatis cras sed felis eget. Arcu cursus vitae congue mauris rhoncus. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Vulputate ut pharetra sit amet. Accumsan in nisl nisi scelerisque. Imperdiet nulla malesuada pellentesque elit eget. Diam vulputate ut pharetra sit amet aliquam. Lobortis mattis aliquam faucibus purus. Turpis egestas integer eget aliquet nibh. In hac habitasse platea dictumst.";



 if ($newtext =~ /(quel\s\S\w+)/){
 	print "Match! : $1\n";
 }
 else {
 	print "No matches found :(";
 }



}
main();